bootstrap.servers=kafka:9092
group.id=connect-cluster
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.topic=neon_cdc_connect_offsets
config.storage.topic=neon_cdc_connect_configs
status.storage.topic=neon_cdc_connect_statuses